services:
  - type: web
    name: stayconnected365-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: ESIM_API_KEY
        sync: false
      - key: ESIM_SECRET_KEY
        sync: false 